# Generated by Django 4.0.6 on 2022-09-24 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_title_alter_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_url',
            field=models.URLField(null=True),
        ),
    ]
